### ISSUE TITLE
I do not know how to get my test function to run...

### ISSUE THREAD

**Issue by samanthaduke** [Samantha-Eaton-Duke/547#17]
https://github.com/Samantha-Eaton-Duke/547/blob/104184298a5aa918f124624956beeb3480f12828/test_line.py

I have tried various methods to unit test my function but it is not working and I keep getting an error that: In test_line: function uses no argument

**Comment by dward2** [comment]
Here is your parametrize decorator:
https://github.com/Samantha-Eaton-Duke/547/blob/104184298a5aa918f124624956beeb3480f12828/test_line.py#L5-L7

It decorates the following function:
https://github.com/Samantha-Eaton-Duke/547/blob/104184298a5aa918f124624956beeb3480f12828/test_line.py#L16-L20

The error you are receiving says "test_line: funciton has no argument".

So, what is the difference between your decorator and your function definition that  might lead to an error about having "no arguments".  

As an aid, refer to the information at https://github.com/dward2/BME547/blob/main/Lectures/robust_testing.md#testing-multiple-cases-using-parametrized-testing for how we set up the parametrize decorator.

**Comment by samanthaduke** [comment]
It is working now, but I still need to write a unit test for each function
